# Site settings
title: Chadev
description: "A community for Chattanooga Developers"
url: http://localhost:3000

# Custom collection settings
collections:
  devs:
    output: false

# Build settings
markdown: kramdown
permalink: pretty
highlights: false
exclude:
    -   bower_components
    -   node_modules
    -   bower.json
    -   bower.json
    -   gulpfile.js
    -   package.json
