# Site settings
title: Chadev
description: "A community for Chattanooga Developers"
url: http://chadev.github.io
collections:
    profiles:
        output: true

# Build settings
markdown: kramdown
permalink: pretty
highlights: false
exclude:
    -   bower_components
    -   node_modules
    -   bower.json
    -   bower.json
    -   gulpfile.js
    -   package.json
defaults:
    -
        scope:
            path: profiles
        values:
            layout: profile
