# Site settings
title: CodeXX
description: "CodeXX"
url: http://codexx.github.io

# Links to include in header/footer
links:
  - title: Members
    url: /devs

# Custom collection settings
collections:
  groups:
    output: false
  devs:
    output: false

# Build settings
markdown: kramdown
permalink: pretty
highlights: false
exclude:
    -   bower_components
    -   node_modules
    -   bower.json
    -   bower.json
    -   gulpfile.js
    -   package.json

sass:
  sass_dir: assets/sass
  style: :compressed

# Gravatar vars
gravatar_sizes:
  devs: 300
  groups: 300
  members: 300
